
```{r}
source('./baseRscript.R')
library(scales)
library(plotrix)
```

#Reads Zanini table and Bacheler
```{r}
read.table("../Output/freqPatTs_Zanini.csv",sep=",",header=TRUE,row.names=1)->freqPatTsZanini
colMeansTsZanini<-apply(freqPatTsZanini, 2 , mean, na.rm=TRUE)

read.table("../Output/freqPatTs_Bacheler.csv",sep=",",header=TRUE,row.names=1)->freqPatTs0
#calculate mean frequencies
MeanFreq<-apply(freqPatTs0, 2 , mean, na.rm=TRUE)

```

#Bacheler DF
```{r}
OverviewDF<-data.frame(num=1:984,MeanFreq,TypeOfSite)

#Mut rates and sel coefficients
read.csv("../Data/HIVMutRates/HIVMutRates.csv")->mutrates
OverviewDF$TSmutrate<-0

######It seems I need to run these [] first in order to get the mutrates correctly

OverviewDF$TSmutrate[OverviewDF$WTnt=="a"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="AG"]
print(OverviewDF$TSmutrate[OverviewDF$WTnt=="a"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="AG"])

OverviewDF$TSmutrate[OverviewDF$WTnt=="c"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="CU"]
print(OverviewDF$TSmutrate[OverviewDF$WTnt=="c"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="CU"])

OverviewDF$TSmutrate[OverviewDF$WTnt=="g"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="GA"]
print(OverviewDF$TSmutrate[OverviewDF$WTnt=="g"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="GA"])

OverviewDF$TSmutrate[OverviewDF$WTnt=="t"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="UC"]
print(OverviewDF$TSmutrate[OverviewDF$WTnt=="t"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="UC"])

for (i in 1:984){
OverviewDF$EstSelCoeff[i] = EstimatedS(OverviewDF$TSmutrate[i],OverviewDF$MeanFreq[i])}

OverviewDF$WTnt<-consensusB
#WT AAs 
OverviewDF$WTAA<-""
for (i in 1:984){
    if (i%%3==1) OverviewDF$WTAA[i] = seqinr::translate(OverviewDF$WTnt[c(i,i+1,i+2)])
    if (i%%3==2) OverviewDF$WTAA[i] = seqinr::translate(OverviewDF$WTnt[c(i-1,i,i+1)])
    if (i%%3==0) OverviewDF$WTAA[i] = seqinr::translate(OverviewDF$WTnt[c(i-2,i-1,i)])
}

OverviewDF$MUTAA<-""
#MUT AAs
for (i in 1:984){
    if (i%%3==1) OverviewDF$MUTAA[i] = seqinr::translate(c(transition(OverviewDF$WTnt[i]),OverviewDF$WTnt[c(i+1,i+2)]))
    if (i%%3==2) OverviewDF$MUTAA[i] = seqinr::translate(c(OverviewDF$WTnt[c(i-1)],transition(OverviewDF$WTnt[i]),OverviewDF$WTnt[c(i+1)]))
    if (i%%3==0) OverviewDF$MUTAA[i] = seqinr::translate(c(OverviewDF$WTnt[c(i-2,i-1)],transition(OverviewDF$WTnt[i])))
}

#Add whether AA change is drastic 
OverviewDF$bigAAChange<-0

for(i in 1:nrow(OverviewDF)){
    WT <- amCat(OverviewDF[i,'WTAA'])
    MUT <- amCat(OverviewDF[i,'MUTAA'])
    if (WT == MUT){ OverviewDF$bigAAChange[i] <- 0 
    }else{
        OverviewDF$bigAAChange[i] <- 1
    }
}

#Add whetehr makes CpG 
OverviewDF$makesCpG <- 0
for(i in 1:nrow(OverviewDF)){
    trip <- OverviewDF$WTnt[c(i-1, i, i + 1)]
    if(trip[1] == "c" & trip[2] == "a" ){
        OverviewDF$makesCpG[i] <- 1
    }
    if(trip[2] == "t" & trip[3] == "g"){
       OverviewDF$makesCpG[i] <- 1
    }
}

OverviewDF$ProRT<-c(rep("Pro",297),rep("RT",687))
OverviewDF$AAnum<-c(sort(rep(1:99,3)),sort(rep(1:229,3)))
write.csv(OverviewDF,"../Output/OverviewSelCoeff_Bacheler.csv")

#colors
OverviewDFOrderedByFreq <- OverviewDF[order(MeanFreq),] 
OverviewDFOrderedByFreq$color<-""
for (i in 1:984){
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="syn") OverviewDFOrderedByFreq$color[i] = "darkolivegreen3"
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="nonsyn") OverviewDFOrderedByFreq$color[i] = "red"
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="stop") OverviewDFOrderedByFreq$color[i] = "black"
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="res") OverviewDFOrderedByFreq$color[i] = "purple"
}
```


#Zanini DF
```{r}
#PSP Nov 11 2015 I removed lowerConf and upperConf here because we no longer calculate them
#x<-data.frame(num=1:984,colMeansTs,TypeOfSite,lowerConf,upperConf)
#PSP Nov 11 2015 I renamed x OverviewDFZanini and newdata OverviewDFZaniniOrderedByFreq


numsitesZanini<-length(colMeansTsZanini)
OverviewDFZanini<-data.frame(num=1:numsitesZanini,colMeansTsZanini)

OverviewDFZanini$TypeOfSite<-TypeOfSite[1:numsitesZanini]
OverviewDFZanini$TypeOfSite[1:39]<-"overlap"
OverviewDFZanini$TypeOfSite[which(consensusB != consensusC | consensusC != consensus01AE)]<-"exclude"


OverviewDFZanini$WTnt<-consensusB[1:numsitesZanini]

#Mut rates and sel coefficients
read.csv("../Data/HIVMutRates/HIVMutRates.csv")->mutrates
OverviewDFZanini$TSmutrate<-0
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="a"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="AG"]
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="c"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="CU"]
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="g"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="GA"]
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="t"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="UC"]

for (i in 1:984){
OverviewDFZanini$EstSelCoeff[i] = EstimatedS(OverviewDFZanini$TSmutrate[i],OverviewDFZanini$colMeansTsZanini[i])}

#OverviewDFZanini$EstSelCoeff= OverviewDFZanini$TSmutrate/OverviewDFZanini$colMeansTsZanini
#OverviewDFZanini$EstSelCoeff[OverviewDFZanini$EstSelCoeff>1]<-1

#WT AAs 
OverviewDFZanini$WTAA<-""
for (i in 1:numsitesZanini){
    if (i%%3==1) OverviewDFZanini$WTAA[i] = seqinr::translate(OverviewDFZanini$WTnt[c(i,i+1,i+2)])
    if (i%%3==2) OverviewDFZanini$WTAA[i] = seqinr::translate(OverviewDFZanini$WTnt[c(i-1,i,i+1)])
    if (i%%3==0) OverviewDFZanini$WTAA[i] = seqinr::translate(OverviewDFZanini$WTnt[c(i-2,i-1,i)])
}

OverviewDFZanini$MUTAA<-""
#MUT AAs
for (i in 1:numsitesZanini){
    if (i%%3==1) OverviewDFZanini$MUTAA[i] = seqinr::translate(c(transition(OverviewDFZanini$WTnt[i]),OverviewDFZanini$WTnt[c(i+1,i+2)]))
    if (i%%3==2) OverviewDFZanini$MUTAA[i] = seqinr::translate(c(OverviewDFZanini$WTnt[c(i-1)],transition(OverviewDFZanini$WTnt[i]),OverviewDFZanini$WTnt[c(i+1)]))
    if (i%%3==0) OverviewDFZanini$MUTAA[i] = seqinr::translate(c(OverviewDFZanini$WTnt[c(i-2,i-1)],transition(OverviewDFZanini$WTnt[i])))
}

write.csv(OverviewDFZanini,"../Output/OverviewSelCoeffZanini.csv")

#remove sites that are different between A and B subtypes / ALL B subtype, except pat 6 is subtype C. 
OverviewDFZanini<-OverviewDFZanini[which(consensusC==consensusB),]

#colors
OverviewDFZaniniOrderedByFreq <- OverviewDFZanini[order(OverviewDFZanini$colMeansTsZanini),] 
OverviewDFZaniniOrderedByFreq <- OverviewDFZaniniOrderedByFreq[!is.na(OverviewDFZaniniOrderedByFreq$colMeansTsZanini),] 
OverviewDFZaniniOrderedByFreq$color<-""
OverviewDFZaniniOrderedByFreq$NTcolor<-""
for (i in 1:length(OverviewDFZaniniOrderedByFreq$color)){
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="syn") OverviewDFZaniniOrderedByFreq$color[i] = "darkolivegreen3"
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="nonsyn") OverviewDFZaniniOrderedByFreq$color[i] = "red"
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="stop") OverviewDFZaniniOrderedByFreq$color[i] = "black"
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="res") OverviewDFZaniniOrderedByFreq$color[i] = "purple"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "a") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "blue"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "c") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "purple"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "g") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "purple"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "t") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "blue"
}
```


#Bach cost Vs Zanini Cost RT

```{r}
#Subsetting points


RTZanASynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297]



##########################
##########################

#T #SYN #no CPG
RTZanTSynNoCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297]




########################
########################

#C #SYN #no CPG

RTZanCSynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297]



########################
########################

#A #SYN #CPG
RTZanASynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297]


#T #SYN #CPG
RTZanTSynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297]

########################
########################
#G #SYN #no CPG
RTZanGSynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297]


#########################
#########################
#A #NONSYN #no CPG
RTZanANonSynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0]


#T #NONSYN #no CPG
RTZanTNonSynNoCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0]

#A #NONSYN #CPG
RTZanANonSynCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0]

#T #NONSYN #CPG
#ZanTNonSynCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

##################################################
##################################################
##With big AA change

#A #NONSYN #no CPG

RTZanANoSynNoCPGAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1]



#T #NONSYN #no CPG
RTZanTNoSynNoCPGAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1]

#A #NONSYN #CPG
RTZanANoSynCPGAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1]

#T #NONSYN #CPG
RTZanTNoSynCPGAA <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1]
       
###################################################
##################################################
#no big AA change

#C #NONSYN no big AA change
RTZanCNoSynNOAA <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0]



################################################
################################################
#G #NONSYN no big AA change
RTZanGNoSynNOAA <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0]



############################
############################
#C #NONSYN bigAAChange
RTZanCNONSynBigAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1]


###################
###################
#G #NONSYN bigAAChange
RTZanGNonSynBigAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1]


########################
######################
#nonsense
RTnonsense <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num>297]


#####################
#####################
#resistance
RTresistance<-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num>297]

```

```{r}
#With Labels
library(RColorBrewer)

linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler RT Cost Vs Zanini RT Cost",ylim=c(log(0.000001),log(1)),xlim=c(log(0.000001), log(1)), xlab = "Zanini RT Cost", ylab = "Bacheler RT Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
     #ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.000001,0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.000001,0.00001,0.0001, 0.001, 0.010, 0.100,1.000)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)
axis(2,labels = c(0.000001,0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.000001,0.00001,0.0001, 0.001, 0.010, 0.100,1.000)),las=1)


#A #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanASynNOCPG]),log(OverviewDF$EstSelCoeff[RTZanASynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#T #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTSynNoCPG]),log(OverviewDF$EstSelCoeff[RTZanTSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanCSynNoCPG]),log(OverviewDF$EstSelCoeff[RTZanCSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

points(log(1*10^-6),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[11])
text(log(1*10^-6),log(3.4*10^-6),pos=4,"A/T/C, syn, no CpG")

#######
#A #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanASynCPG]),log(OverviewDF$EstSelCoeff[RTZanASynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

#T #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTSynCPG]),log(OverviewDF$EstSelCoeff[RTZanTSynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

points(log(1*10^-6),log(2.2*10^-6),pch=24,bg=brewer.pal(11, "Spectral")[10])
text(log(1*10^-6),log(2.2*10^-6),pos=4,"A/T, syn, CpG")
######
#G #SYN #No CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanGSynNOCPG]),log(OverviewDF$EstSelCoeff[RTZanGSynNOCPG]),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(log(1*10^-6),log(1.4*10^-6),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(log(1*10^-6),log(1.4*10^-6),pos=4,"G, syn")


#####

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANonSynNOCPG]),log(OverviewDF$EstSelCoeff[RTZanANonSynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

points(log(1*10^-5),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(log(1*10^-5),log(3.4*10^-6),pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTNonSynNoCPG ]),log(OverviewDF$EstSelCoeff[RTZanTNonSynNoCPG ]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANonSynCPG]),log(OverviewDF$EstSelCoeff[RTZanANonSynCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
 
####

#With big AA change

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[RTZanANoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

points(log(1*10^-5),log(2.2*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(log(1*10^-5),log(2.2*10^-6),pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTNoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[RTZanTNoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANoSynCPGAA]),log(OverviewDF$EstSelCoeff[RTZanANoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#T #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTNoSynCPGAA]),log(OverviewDF$EstSelCoeff[RTZanTNoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

########

#no big AA change

#C #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[RTZanCNoSynNOAA]),log(OverviewDF$EstSelCoeff[RTZanCNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)

points(log(1*10^-5),log(1.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(log(1*10^-5),log(1.4*10^-6),pos=4,"C, non-syn, no drastic AA change")

######
#G #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[RTZanGNoSynNOAA]),log(OverviewDF$EstSelCoeff[RTZanGNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)

points(log(1*10^-3),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(log(1*10^-3),log(3.4*10^-6),pos=4,"G, non-syn, no drastic AA change")

#######
#C #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[RTZanCNONSynBigAA]),log(OverviewDF$EstSelCoeff[RTZanCNONSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)

points(log(1*10^-3),log(2.2*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(log(1*10^-3),log(2.2*10^-6),pos=4,"C, non-syn, drastic AA change")
#######
#G #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[RTZanGNonSynBigAA]),log(OverviewDF$EstSelCoeff[RTZanGNonSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)

points(log(1*10^-3),log(1.4*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(log(1*10^-3),log(1.4*10^-6),pos=4,"G, non-syn, drastic AA change")
#######
#nonsense
points(log(OverviewDFZanini$EstSelCoeff[RTnonsense]),log(OverviewDF$EstSelCoeff[RTnonsense]),pch=22,bg=1,col=1)

points(log(1*10^-1),log(3.4*10^-6),pch=22,bg=1,col=1)
text(log(1*10^-1),log(3.4*10^-6),pos=4,"nonsense")

#######
#resistance
points(log(OverviewDFZanini$EstSelCoeff[RTresistance]),log(OverviewDF$EstSelCoeff[RTresistance]),pch=8,bg=1,col=1)

points(log(1*10^-1),log(2.2*10^-6),pch=8,bg=1,col=1)
text(log(1*10^-1),log(2.2*10^-6),pos=4,"resistance")
```




```{r}
#Everything
# A/T/C Syn No CPG
#Plotting both Zanini and bacheler's fitness cost together.

#pdf("../Output/EstSelCoeffRTZanBachNALabel.pdf",width=12,height=8)
par(mfrow=c(1,1))

linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler RT Cost Vs Zanini RT Cost",ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini RT Cost", ylab = "Bacheler RT Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
     #ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.001, 0.010, 0.100,1.000)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)
axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.001, 0.010, 0.100,1.000)),las=1)


#A #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanASynNOCPG]),log(OverviewDF$EstSelCoeff[RTZanASynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#T #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTSynNoCPG]),log(OverviewDF$EstSelCoeff[RTZanTSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanCSynNoCPG]),log(OverviewDF$EstSelCoeff[RTZanCSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

points(log(1*10^-6),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[11])
text(log(1*10^-6),log(3.4*10^-6),pos=4,"A/T/C, syn, no CpG")

#######
#A #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanASynCPG]),log(OverviewDF$EstSelCoeff[RTZanASynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

#T #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTSynCPG]),log(OverviewDF$EstSelCoeff[RTZanTSynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

points(log(1*10^-6),log(2.2*10^-6),pch=24,bg=brewer.pal(11, "Spectral")[10])
text(log(1*10^-6),log(2.2*10^-6),pos=4,"A/T, syn, CpG")
######
#G #SYN #No CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanGSynNOCPG]),log(OverviewDF$EstSelCoeff[RTZanGSynNOCPG]),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(log(1*10^-6),log(1.4*10^-6),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(log(1*10^-6),log(1.4*10^-6),pos=4,"G, syn")


#####

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANonSynNOCPG]),log(OverviewDF$EstSelCoeff[RTZanANonSynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

points(log(1*10^-5),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(log(1*10^-5),log(3.4*10^-6),pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTNonSynNoCPG ]),log(OverviewDF$EstSelCoeff[RTZanTNonSynNoCPG ]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANonSynCPG]),log(OverviewDF$EstSelCoeff[RTZanANonSynCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
 
####

#With big AA change

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[RTZanANoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

points(log(1*10^-5),log(2.2*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(log(1*10^-5),log(2.2*10^-6),pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTNoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[RTZanTNoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanANoSynCPGAA]),log(OverviewDF$EstSelCoeff[RTZanANoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#T #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[RTZanTNoSynCPGAA]),log(OverviewDF$EstSelCoeff[RTZanTNoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

########

#no big AA change

#C #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[RTZanCNoSynNOAA]),log(OverviewDF$EstSelCoeff[RTZanCNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)

points(log(1*10^-5),log(1.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(log(1*10^-5),log(1.4*10^-6),pos=4,"C, non-syn, no drastic AA change")

######
#G #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[RTZanGNoSynNOAA]),log(OverviewDF$EstSelCoeff[RTZanGNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)

points(log(1*10^-3),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(log(1*10^-3),log(3.4*10^-6),pos=4,"G, non-syn, no drastic AA change")

#######
#C #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[RTZanCNONSynBigAA]),log(OverviewDF$EstSelCoeff[RTZanCNONSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)


#######
#G #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[RTZanGNonSynBigAA]),log(OverviewDF$EstSelCoeff[RTZanGNonSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
#######
#nonsense
points(log(OverviewDFZanini$EstSelCoeff[RTnonsense]),log(OverviewDF$EstSelCoeff[RTnonsense]),pch=22,bg=1,col=1)

#######
#resistance
points(log(OverviewDFZanini$EstSelCoeff[RTresistance]),log(OverviewDF$EstSelCoeff[RTresistance]),pch=8,bg=1,col=1)

#dev.off()

```

