


```{r}
#Gabriella's work directory
#setwd("C:/Users/Gaby/Dropbox/2016Project_Gabriella _Abdul/Rscripts")
#make sure package "pegas" is downloaded

source('./baseRscript.R')
library(scales)
library(plotrix)
```


```{r}
read.table("../Output/freqPatTs_Zanini.csv",sep=",",header=TRUE,row.names=1)->freqPatTsZanini
colMeansTsZanini<-apply(freqPatTsZanini, 2 , mean, na.rm=TRUE)
```

```{r}
#GT 2/15/17 after I ran line 22 and 23 I don't see any missing numbers in "num"
# from the "typeofsite"" num is still the same
# same for the mutation rate chuck
# no changes for est cost, WTAA chunk, mutaa, bigAA, makes CPGs, ProRT and AAnum
# 2/17/17 Running everthing I notice the 6 was missing, So I am going to run and everything to see where the 6 was missing
#When I run the whole chuck (after erasering environmwent/history) num is missing, so maybe I have to run each individual chunk and see if 6 is truely missing

#num was still here
numsitesZanini<-length(colMeansTsZanini)
OverviewDFZanini<-data.frame(num=1:numsitesZanini,colMeansTsZanini)

#num is still here (I notice it was an exclude site)
OverviewDFZanini$TypeOfSite<-TypeOfSite[1:numsitesZanini]
OverviewDFZanini$TypeOfSite[1:39]<-"overlap"
OverviewDFZanini$TypeOfSite[which(consensusB != consensusC | consensusC != consensus01AE)]<-"exclude"

OverviewDFZanini$WTnt<-consensusB[1:numsitesZanini]



#Mut rates and sel coefficients
#num 6 still here
read.csv("../Data/HIVMutRates/HIVMutRates.csv")->mutrates
OverviewDFZanini$TSmutrate<-0
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="a"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="AG"]
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="c"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="CU"]
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="g"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="GA"]
OverviewDFZanini$TSmutrate[OverviewDFZanini$WTnt=="t"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="UC"]

#num 6 still here
for (i in 1:984){
OverviewDFZanini$EstSelCoeff[i] = EstimatedS(OverviewDFZanini$TSmutrate[i],OverviewDFZanini$colMeansTsZanini[i])}

#OverviewDFZanini$EstSelCoeff= OverviewDFZanini$TSmutrate/OverviewDFZanini$colMeansTsZanini
#OverviewDFZanini$EstSelCoeff[OverviewDFZanini$EstSelCoeff>1]<-1

#WT AAs 
OverviewDFZanini$WTAA<-""
for (i in 1:numsitesZanini){
    if (i%%3==1) OverviewDFZanini$WTAA[i] = seqinr::translate(OverviewDFZanini$WTnt[c(i,i+1,i+2)])
    if (i%%3==2) OverviewDFZanini$WTAA[i] = seqinr::translate(OverviewDFZanini$WTnt[c(i-1,i,i+1)])
    if (i%%3==0) OverviewDFZanini$WTAA[i] = seqinr::translate(OverviewDFZanini$WTnt[c(i-2,i-1,i)])
}

OverviewDFZanini$MUTAA<-""
#MUT AAs
for (i in 1:numsitesZanini){
    if (i%%3==1) OverviewDFZanini$MUTAA[i] = seqinr::translate(c(transition(OverviewDFZanini$WTnt[i]),OverviewDFZanini$WTnt[c(i+1,i+2)]))
    if (i%%3==2) OverviewDFZanini$MUTAA[i] = seqinr::translate(c(OverviewDFZanini$WTnt[c(i-1)],transition(OverviewDFZanini$WTnt[i]),OverviewDFZanini$WTnt[c(i+1)]))
    if (i%%3==0) OverviewDFZanini$MUTAA[i] = seqinr::translate(c(OverviewDFZanini$WTnt[c(i-2,i-1)],transition(OverviewDFZanini$WTnt[i])))
}

#Add whether AA change is drastic 
OverviewDFZanini$bigAAChange<-0

for(i in 1:nrow(OverviewDFZanini)){
    WT <- amCat(OverviewDFZanini[i,'WTAA'])
    MUT <- amCat(OverviewDFZanini[i,'MUTAA'])
    if (WT == MUT){ OverviewDFZanini$bigAAChange[i] <- 0 
    }else{
        OverviewDFZanini$bigAAChange[i] <- 1
    }
}


OverviewDFZanini$makesCpG <- 0
for(i in 1:nrow(OverviewDFZanini)){
    trip <- OverviewDFZanini$WTnt[c(i-1, i, i + 1)]
    if(trip[1] == "c" & trip[2] == "a" ){
        OverviewDFZanini$makesCpG[i] <- 1
    }
    if(trip[2] == "t" & trip[3] == "g"){
       OverviewDFZanini$makesCpG[i] <- 1
    }
}


######### (Testing ProRT Zanini)
OverviewDFZanini$ProRT<-c(rep("Pro",297),rep("RT",687)) #Error message: Error in `$<-.data.frame`(`*tmp*`, "ProRT", value = c("Pro", "Pro", "Pro",  : replacement has 984 rows, data has 903

#GT 2/10/17 I changed RT to 606 instead of 687 and that seems to work


OverviewDFZanini$AAnum<-c(sort(rep(1:99,3)),sort(rep(1:229,3)))
#Error in `$<-.data.frame`(`*tmp*`, "AAnum", value = c(1L, 1L, 1L, 2L,  : replacement has 984 rows, data has 903

#GT 2/13/17 I changed the rep 229 to 202


#########

write.csv(OverviewDFZanini,"../Output/OverviewSelCoeffZanini.csv")



#remove sites that are different between A and B subtypes / ALL B subtype, except pat 6 is subtype C. 
#(so this line of code removes num=6 and maybe the other numbers too?- GT 2/22/17) why do we need this line of code? I will try to run the code without this line and see if it makes a difference. does this remove the exculde type of sites?

#OverviewDFZanini<-OverviewDFZanini[which(consensusC==consensusB),]




#colors########(Different)
OverviewDFZaniniOrderedByFreq <- OverviewDFZanini[order(OverviewDFZanini$colMeansTsZanini),] 
OverviewDFZaniniOrderedByFreq <- OverviewDFZaniniOrderedByFreq[!is.na(OverviewDFZaniniOrderedByFreq$colMeansTsZanini),] 
OverviewDFZaniniOrderedByFreq$color<-""
OverviewDFZaniniOrderedByFreq$NTcolor<-""
for (i in 1:length(OverviewDFZaniniOrderedByFreq$color)){
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="syn") OverviewDFZaniniOrderedByFreq$color[i] = "darkolivegreen3"
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="nonsyn") OverviewDFZaniniOrderedByFreq$color[i] = "red"
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="stop") OverviewDFZaniniOrderedByFreq$color[i] = "black"
    if (OverviewDFZaniniOrderedByFreq$TypeOfSite[i]=="res") OverviewDFZaniniOrderedByFreq$color[i] = "purple"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "a") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "blue"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "c") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "purple"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "g") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "purple"
    if (OverviewDFZaniniOrderedByFreq$WTnt[i] == "t") OverviewDFZaniniOrderedByFreq$NTcolor[i] = "blue"
}
```


```{r}
#Subsetting the points
#GT 3/10/17 These are the four catergories I notice Type of sites (Nonsyn, syn), (exlcude, res, nonsense), WTnt (A, C, G, T), No CPG or CPG, Drastic AA and non drastic AA




####### EXclude Sites

Exclude <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num<=297]

########  A/T/C Syn no CPG                             
#A #SYN #no CPG
ASynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]

#T #SYN #no CPG
TSynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]

#C #SYN #no CPG
CSynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]

######## A/T Syn CPG
#A #SYN #CPG
ASynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297]

#T #SYN #CPG
TSynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297]

######## G Syn no CPG

#G #SYN #no CPG
GSynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]


######## A/T Nonsyn No CPG
#A #NONSYN #no CPG
ANonsynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]


#T #NONSYN #no CPG
TNonsynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]
       
####### A/T Nonsyn CPG
#A #NONSYN #CPG
ANonsynCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

#T #NONSYN #CPG 
TNonsynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

#########With big AA change##########

###### A/T Nonsyn (no CPG) Drastic AA

#A #NONSYN #no CPG
AAANonsynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]


#T #NONSYN #no CPG
AATNonsynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]

#A #NONSYN #CPG 
#Why is this one in this catergoies? it has a CPG while the other two don't have CPG
#This was coded wrong

#AAANonsynCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]


#########no big AA change########

#C #NONSYN no big AA change #No CpG
NOAACNonsynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

#############

#G #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,2*10^-5,pos=4,"G, non-syn, no drastic AA change")

#C #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[3])

points(200,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(203,1.4*10^-5,pos=4,"C, non-syn, drastic AA change")

#G #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,1*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,1*10^-5,pos=4,"G, non-syn, drastic AA change")

#nonsense
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297],pch=22,col=2,bg=1)

points(280,2*10^-5,pch=22,bg=1,col=1)
text(283,2*10^-5,pos=4,"nonsense")

#resistance
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297],pch=8,col=1,bg=1)

points(280,1.4*10^-5,pch=8,bg=1,col=1)
text(283,1.4*10^-5,pos=4,"resistance")

```


```{r}
par(mfrow=c(1,1))
#make log scale
#plot(OverviewDFZanini$num[40:297],OverviewDFZanini$EstSelCoeff[40:297],log="y", 
#     ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Protease(Zanini)", xaxt="n",yaxt="n",col="darkgrey",t="c",pch=".",
 #    ylim=c(0.9*10^-5,1),
  #   xlim=c(250, 297))
#axis(1,at=3*c(14,35,55,75,95)-1,labels=c(14,35,55,75,95))
#axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))

plot(OverviewDFZanini$num[180:182],OverviewDFZanini$EstSelCoeff[180:182],log="y", 
     ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Protease(Zanini)", xaxt="n",yaxt="n",col="darkgrey",t="c",pch=".",
     ylim=c(0.9*10^-5,1))
axis(1,at=3*c(14,35,55,75,95)-1,labels=c(14,35,55,75,95))
axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))

#Add colors for different types of sites

#visualize excluded points
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num<=297&OverviewDFZanini$num>=40],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num<=297&OverviewDFZanini$num>=40],pch=21,bg=1)

points(280,1*10^-5,pch=21,bg=1)
text(283,1*10^-5,pos=4,"exclude")
         
#A #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

points(45,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[11])
text(48,2*10^-5,pos=4,"A/T/C, syn, no CpG")

#T #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])


#A #SYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],pch=24,bg=brewer.pal(11, "Spectral")[10])

points(45,1.4*10^-5,pch=24,bg=brewer.pal(11, "Spectral")[10])
text(48,1.4*10^-5,pos=4,"A/T, syn, CpG")

#T #SYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],pch=24,bg=brewer.pal(11, "Spectral")[10])


#G #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(45,1*10^-5,pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(48,1*10^-5,pos=4,"G, syn")

#A #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

points(100,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(103,2*10^-5,pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#A #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#T #NONSYN #CPG ###(I did not see a point)
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

##################With big AA change

#A #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

points(100,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(103,1.4*10^-5,pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#A #NONSYN #CPG (This is coded wrong)
#points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

##### 3/10/17 added code
#A #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#T #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])
#####

#no big AA change

#C #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[3])

points(100,1*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(103,1*10^-5,pos=4,"C, non-syn, no drastic AA change")

#G #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,2*10^-5,pos=4,"G, non-syn, no drastic AA change")

#C #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[3])

points(200,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(203,1.4*10^-5,pos=4,"C, non-syn, drastic AA change")

#G #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,1*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,1*10^-5,pos=4,"G, non-syn, drastic AA change")

#nonsense
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297],pch=22,col=2,bg=1)

points(280,2*10^-5,pch=22,bg=1,col=1)
text(283,2*10^-5,pos=4,"nonsense")

#resistance
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297],pch=8,col=1,bg=1)

points(280,1.4*10^-5,pch=8,bg=1,col=1)
text(283,1.4*10^-5,pos=4,"resistance")
```



```{r}
#GT 2/17/17 It seems I need to run this whole chunck it to work otherwise I will get this error "Error in plot.xy(xy.coords(x, y), type = type, ...) : plot.new has not been called yet" even though I set up the plot already.
#I wonder if I running the whole chuck instead just individual changes?

library(RColorBrewer)

#pdf("../Output/EstSelCoeffPROZanini.pdf",width=12,height=8)
#pdf("../Output/EstSelCoeffPROZanini(NEW).pdf",width=12,height=8)
#pdf("../Output/EstSelCoeffPROZanini(Updated).pdf",width=12,height=8)
#pdf("../Output/EstSelCoeffPROZanini(Latest).pdf",width=12,height=8)
par(mfrow=c(1,1))
#make log scale
#plot(OverviewDFZanini$num[40:297],OverviewDFZanini$EstSelCoeff[40:297],log="y", 
#     ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Protease(Zanini)", xaxt="n",yaxt="n",col="darkgrey",t="c",pch=".",
 #    ylim=c(0.9*10^-5,1),
  #   xlim=c(250, 297))
#axis(1,at=3*c(14,35,55,75,95)-1,labels=c(14,35,55,75,95))
#axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))

plot(OverviewDFZanini$num[40:297],OverviewDFZanini$EstSelCoeff[40:297],log="y", 
     ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Protease(Zanini)", xaxt="n",yaxt="n",col="darkgrey",t="c",pch=".",
     ylim=c(0.9*10^-5,1))
axis(1,at=3*c(14,35,55,75,95)-1,labels=c(14,35,55,75,95))
axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))

#Add colors for different types of sites

#visualize excluded points
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num<=297&OverviewDFZanini$num>=40],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num<=297&OverviewDFZanini$num>=40],pch=21,bg=1)

points(280,1*10^-5,pch=21,bg=1)
text(283,1*10^-5,pos=4,"exclude")
         
#A #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

points(45,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[11])
text(48,2*10^-5,pos=4,"A/T/C, syn, no CpG")

#T #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])


#A #SYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],pch=24,bg=brewer.pal(11, "Spectral")[10])

points(45,1.4*10^-5,pch=24,bg=brewer.pal(11, "Spectral")[10])
text(48,1.4*10^-5,pos=4,"A/T, syn, CpG")

#T #SYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297],pch=24,bg=brewer.pal(11, "Spectral")[10])


#G #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(45,1*10^-5,pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(48,1*10^-5,pos=4,"G, syn")

#A #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

points(100,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(103,2*10^-5,pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#A #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#T #NONSYN #CPG ###(I did not see a point)
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

##################With big AA change

#A #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

points(100,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(103,1.4*10^-5,pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#A #NONSYN #CPG (This is coded wrong)
#points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

##### 3/10/17 added code
#A #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#T #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])
#####

#no big AA change

#C #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[3])

points(100,1*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(103,1*10^-5,pos=4,"C, non-syn, no drastic AA change")

#G #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,2*10^-5,pos=4,"G, non-syn, no drastic AA change")

#C #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[3])

points(200,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(203,1.4*10^-5,pos=4,"C, non-syn, drastic AA change")

#G #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,1*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,1*10^-5,pos=4,"G, non-syn, drastic AA change")

#nonsense
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297],pch=22,col=2,bg=1)

points(280,2*10^-5,pch=22,bg=1,col=1)
text(283,2*10^-5,pos=4,"nonsense")

#resistance
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297],pch=8,col=1,bg=1)

points(280,1.4*10^-5,pch=8,bg=1,col=1)
text(283,1.4*10^-5,pos=4,"resistance")

#dev.off()
```


#RT Zanini plot

```{r}
#GT 3/20/17 I notice a fewer green triginals. I wonder if they turned into exclude sites

#Make a figure with the selection coefficients across RT
#pdf("../Output/EstSelCoeffRT(Zanini).pdf",width=12,height=8)
par(mfrow=c(1,1))
#make log scale
plot(OverviewDFZanini$num[298:984],OverviewDFZanini$EstSelCoeff[298:984],log="y",      ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Reverse Transcriptase Zanini", xaxt="n",yaxt="n",col="darkgrey",
     t="c",pch=".",
     ylim=c(0.9*10^-5,1))
axis(1,at=298+3*seq(20,228,by=20)-1,labels=seq(20,228,by=20))
axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))
#Add colors for different types of sites

#Exclude sites
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="exclude"&OverviewDFZanini$num>297],pch=21,bg=1)

points(298+620,1*10^-5,pch=21,bg=1)
text(298+623,1*10^-5,pos=4,"exclude")


#A #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],pch=21,bg=brewer.pal(11, "Spectral")[11])

points(298+45,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[11])
text(298+48,2*10^-5,pos=4,"A/T/C, syn, no CpG")

#T #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#A #SYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297],pch=24,bg=brewer.pal(11, "Spectral")[10])

points(298+45,1.4*10^-5,pch=24,bg=brewer.pal(11, "Spectral")[10])
text(298+48,1.4*10^-5,pos=4,"A/T, syn, CpG")

#T #SYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297],pch=24,bg=brewer.pal(11, "Spectral")[10])

#G #SYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297],pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(298+45,1*10^-5,pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(298+48,1*10^-5,pos=4,"G, syn")

#A #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

points(298+180,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(298+183,2*10^-5,pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#A #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#T #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#With big AA change (3/15/17)

#A #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

points(298+180,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(298+183,1.4*10^-5,pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#A #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#T #NONSYN #CPG
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])


#no big AA change

#C #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[3])

points(298+180,1*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(298+183,1*10^-5,pos=4,"C, non-syn, no drastic AA change")

#G #NONSYN no big AA change
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[1])

points(298+400,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(298+403,2*10^-5,pos=4,"G, non-syn, no drastic AA change")

#C #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[3])

points(298+400,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(298+403,1.4*10^-5,pos=4,"C, non-syn, drastic AA change")

#G #NONSYN bigAAChange
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num>297&OverviewDFZanini$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[1])

points(298+400,1*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(298+403,1*10^-5,pos=4,"G, non-syn, drastic AA change")

#nonsense
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num>297],pch=22,col=2,bg=1)

points(298+620,2*10^-5,pch=22,bg=1,col=1)
text(298+623,2*10^-5,pos=4,"nonsense")

#resistance
points(OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num>297],OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num>297],pch=8,col=1,bg=1)

points(298+620,1.4*10^-5,pch=8,bg=1,col=1)
text(298+623,1.4*10^-5,pos=4,"resistance")

#dev.off()
```




###Bachelor Plot
```{r}
#read the stored data
#We read a file with WT 0 as threshold, meaning no threshold)
read.table("../Output/freqPatTs_Bacheler.csv",sep=",",header=TRUE,row.names=1)->freqPatTs0
#calculate mean frequencies
MeanFreq<-apply(freqPatTs0, 2 , mean, na.rm=TRUE)
```



```{r}
OverviewDF<-data.frame(num=1:984,MeanFreq,TypeOfSite)

#Mut rates and sel coefficients
read.csv("../Data/HIVMutRates/HIVMutRates.csv")->mutrates
OverviewDF$TSmutrate<-0

#GT 1/12/17 Run the WTnt first before the Tsmutrate

OverviewDF$WTnt<-consensusB

OverviewDF$TSmutrate[OverviewDF$WTnt=="a"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="AG"]


OverviewDF$TSmutrate[OverviewDF$WTnt=="c"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="CU"]


OverviewDF$TSmutrate[OverviewDF$WTnt=="g"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="GA"]


OverviewDF$TSmutrate[OverviewDF$WTnt=="t"]<-mutrates$Probability[mutrates$Nucleotide.substitution=="UC"]



for (i in 1:984){
OverviewDF$EstSelCoeff[i] = EstimatedS(OverviewDF$TSmutrate[i],OverviewDF$MeanFreq[i])}


#WT AAs 
OverviewDF$WTAA<-""
for (i in 1:984){
    if (i%%3==1) OverviewDF$WTAA[i] = seqinr::translate(OverviewDF$WTnt[c(i,i+1,i+2)])
    if (i%%3==2) OverviewDF$WTAA[i] = seqinr::translate(OverviewDF$WTnt[c(i-1,i,i+1)])
    if (i%%3==0) OverviewDF$WTAA[i] = seqinr::translate(OverviewDF$WTnt[c(i-2,i-1,i)])
}

OverviewDF$MUTAA<-""
#MUT AAs
for (i in 1:984){
    if (i%%3==1) OverviewDF$MUTAA[i] = seqinr::translate(c(transition(OverviewDF$WTnt[i]),OverviewDF$WTnt[c(i+1,i+2)]))
    if (i%%3==2) OverviewDF$MUTAA[i] = seqinr::translate(c(OverviewDF$WTnt[c(i-1)],transition(OverviewDF$WTnt[i]),OverviewDF$WTnt[c(i+1)]))
    if (i%%3==0) OverviewDF$MUTAA[i] = seqinr::translate(c(OverviewDF$WTnt[c(i-2,i-1)],transition(OverviewDF$WTnt[i])))
}

#Add whether AA change is drastic 
OverviewDF$bigAAChange<-0

for(i in 1:nrow(OverviewDF)){
    WT <- amCat(OverviewDF[i,'WTAA'])
    MUT <- amCat(OverviewDF[i,'MUTAA'])
    if (WT == MUT){ OverviewDF$bigAAChange[i] <- 0 
    }else{
        OverviewDF$bigAAChange[i] <- 1
    }
}

#Add whetehr makes CpG 
OverviewDF$makesCpG <- 0
for(i in 1:nrow(OverviewDF)){
    trip <- OverviewDF$WTnt[c(i-1, i, i + 1)]
    if(trip[1] == "c" & trip[2] == "a" ){
        OverviewDF$makesCpG[i] <- 1
    }
    if(trip[2] == "t" & trip[3] == "g"){
       OverviewDF$makesCpG[i] <- 1
    }
}

OverviewDF$ProRT<-c(rep("Pro",297),rep("RT",687))
OverviewDF$AAnum<-c(sort(rep(1:99,3)),sort(rep(1:229,3)))
write.csv(OverviewDF,"../Output/OverviewSelCoeff_Bacheler.csv")

#colors
OverviewDFOrderedByFreq <- OverviewDF[order(MeanFreq),] 
OverviewDFOrderedByFreq$color<-""
for (i in 1:984){
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="syn") OverviewDFOrderedByFreq$color[i] = "darkolivegreen3"
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="nonsyn") OverviewDFOrderedByFreq$color[i] = "red"
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="stop") OverviewDFOrderedByFreq$color[i] = "black"
    if (OverviewDFOrderedByFreq$TypeOfSite[i]=="res") OverviewDFOrderedByFreq$color[i] = "purple"
}
```


```{r}
library(RColorBrewer)

#pdf("../Output/EstSelCoeffPRO.pdf",width=12,height=8)
par(mfrow=c(1,1))
#make log scale
plot(OverviewDF$num[40:297],OverviewDF$EstSelCoeff[40:297],log="y", 
     ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Protease", xaxt="n",yaxt="n",col="darkgrey",t="c",pch=".",
     ylim=c(0.9*10^-5,1))
axis(1,at=3*c(14,35,55,75,95)-1,labels=c(14,35,55,75,95))
axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))
#Add colors for different types of sites

#A #SYN #no CPG

points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

points(45,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[11])
text(48,2*10^-5,pos=4,"A/T/C, syn, no CpG")

#T #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#A #SYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num<=297],pch=24,bg=brewer.pal(11, "Spectral")[10])

points(45,1.4*10^-5,pch=24,bg=brewer.pal(11, "Spectral")[10])
text(48,1.4*10^-5,pos=4,"A/T, syn, CpG")

#T #SYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num<=297],pch=24,bg=brewer.pal(11, "Spectral")[10])

#G #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num<=297],pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(45,1*10^-5,pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(48,1*10^-5,pos=4,"G, syn")

#A #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

points(100,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(103,2*10^-5,pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#A #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#T #NONSYN #CPG
#points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#With big AA change

#A #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

points(100,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(103,1.4*10^-5,pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#A #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#T #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num<=297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])


#no big AA change

#C #NONSYN no big AA change
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[3])

points(100,1*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(103,1*10^-5,pos=4,"C, non-syn, no drastic AA change")

#G #NONSYN no big AA change
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,2*10^-5,pos=4,"G, non-syn, no drastic AA change")

#C #NONSYN bigAAChange
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[3])

points(200,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(203,1.4*10^-5,pos=4,"C, non-syn, drastic AA change")

#G #NONSYN bigAAChange
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[1])

points(200,1*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(203,1*10^-5,pos=4,"G, non-syn, drastic AA change")

#nonsense
points(OverviewDF$num[OverviewDF$TypeOfSite=="stop"&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="stop"&OverviewDF$num<=297],pch=22,col=2,bg=1)

points(280,2*10^-5,pch=22,bg=1,col=1)
text(283,2*10^-5,pos=4,"nonsense")

#resistance
points(OverviewDF$num[OverviewDF$TypeOfSite=="res"&OverviewDF$num<=297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="res"&OverviewDF$num<=297],pch=8,col=1,bg=1)

points(280,1.4*10^-5,pch=8,bg=1,col=1)
text(283,1.4*10^-5,pos=4,"resistance")

#dev.off()
```




#RT Plot Bacheler

```{r}
#Make a figure with the selection coefficients across RT
#pdf("../Output/EstSelCoeffRT.pdf",width=12,height=8)
par(mfrow=c(1,1))
#make log scale
plot(OverviewDF$num[298:984],OverviewDF$EstSelCoeff[298:984],log="y", 
     ylab="Estimated Selection Coefficient (cost)", xlab = "Position in Reverse Transcriptase", xaxt="n",yaxt="n",col="darkgrey",
     t="c",pch=".",
     ylim=c(0.9*10^-5,1))
axis(1,at=298+3*seq(20,228,by=20)-1,labels=seq(20,228,by=20))
axis(2,at=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0),labels=c(10^-5,10^-4,10^-3,10^-2,10^-1,10^-0))
#Add colors for different types of sites

#A #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num>297],pch=21,bg=brewer.pal(11, "Spectral")[11])

points(298+45,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[11])
text(298+48,2*10^-5,pos=4,"A/T/C, syn, no CpG")

#T #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num>297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num>297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#A #SYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num>297],pch=24,bg=brewer.pal(11, "Spectral")[10])

points(298+45,1.4*10^-5,pch=24,bg=brewer.pal(11, "Spectral")[10])
text(298+48,1.4*10^-5,pos=4,"A/T, syn, CpG")

#T #SYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num>297],pch=24,bg=brewer.pal(11, "Spectral")[10])

#G #SYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num>297],pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(298+45,1*10^-5,pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(298+48,1*10^-5,pos=4,"G, syn")

#A #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

points(298+180,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(298+183,2*10^-5,pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#A #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#T #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[7])

#With big AA change

#A #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

points(298+180,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(298+183,1.4*10^-5,pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#A #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])

#T #NONSYN #CPG
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==1&OverviewDF$num>297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[5])


#no big AA change

#C #NONSYN no big AA change
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[3])

points(298+180,1*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(298+183,1*10^-5,pos=4,"C, non-syn, no drastic AA change")

#G #NONSYN no big AA change
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==0],pch=21,col=2,bg=brewer.pal(11, "Spectral")[1])

points(298+400,2*10^-5,pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(298+403,2*10^-5,pos=4,"G, non-syn, no drastic AA change")

#C #NONSYN bigAAChange
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[3])

points(298+400,1.4*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(298+403,1.4*10^-5,pos=4,"C, non-syn, drastic AA change")

#G #NONSYN bigAAChange
points(OverviewDF$num[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="nonsyn"&OverviewDF$WTnt=="g"&OverviewDF$makesCpG==0&OverviewDF$num>297&OverviewDF$bigAAChange==1],pch=22,col=2,bg=brewer.pal(11, "Spectral")[1])

points(298+400,1*10^-5,pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(298+403,1*10^-5,pos=4,"G, non-syn, drastic AA change")

#nonsense
points(OverviewDF$num[OverviewDF$TypeOfSite=="stop"&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="stop"&OverviewDF$num>297],pch=22,col=2,bg=1)

points(298+620,2*10^-5,pch=22,bg=1,col=1)
text(298+623,2*10^-5,pos=4,"nonsense")

#resistance
points(OverviewDF$num[OverviewDF$TypeOfSite=="res"&OverviewDF$num>297],OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="res"&OverviewDF$num>297],pch=8,col=1,bg=1)

points(298+620,1.4*10^-5,pch=8,bg=1,col=1)
text(298+623,1.4*10^-5,pos=4,"resistance")

dev.off()
```









#Subsetting both Zanini and Bacheler

```{r}
#Subsetting points

#A #SYN #no CPG

#BachASynNoCPG <- OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297]

#OverviewDF$EstSelCoeff[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#BachASynNoCPG #Check to see which sites are Excluded from zanini

ZanASynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]


#OverviewDFZanini$EstSelCoeff[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297],pch=21,bg=brewer.pal(11, "Spectral")[11])

#ZanASynNOCPG # check the difference Zanini sites

#Make changes 

BachASynNoCPGNEW <- OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="a"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$num>71&OverviewDF$num!=105&OverviewDF$num!=168&OverviewDF$num!=171&OverviewDF$num!=210]
##########################
##########################

#T #SYN #no CPG
ZanTSynNoCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]


#BachTSynNOCPG <- OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297]

BachTSynNOCPGNEW <-OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="t"&OverviewDF$makesCpG==0&OverviewDF$num<=297&OverviewDF$num!=75&OverviewDF$num!=207&OverviewDF$num!=282&OverviewDF$num!=288&OverviewDF$num!=289&OverviewDF$num!=297]

########################
########################

#C #SYN #no CPG

ZanCSynNoCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]

#BachCSynNoCPG <- OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297]

BachCSynNoCPGNEW <-OverviewDF$num[OverviewDF$TypeOfSite=="syn"&OverviewDF$WTnt=="c"&OverviewDF$makesCpG==0&OverviewDF$num<=297]

########################
########################

#A #SYN #CPG
ZanASynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297]


#T #SYN #CPG
ZanTSynCPG <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297]

########################
########################
#G #SYN #no CPG
ZanGSynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="syn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297]


#########################
#########################
#A #NONSYN #no CPG
ZanANonSynNOCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]


#T #NONSYN #no CPG
ZanTNonSynNoCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

#A #NONSYN #CPG
ZanANonSynCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

#T #NONSYN #CPG
#ZanTNonSynCPG <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]

##################################################
##################################################
##With big AA change

#A #NONSYN #no CPG

ZanANoSynNoCPGAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]



#T #NONSYN #no CPG
ZanTNoSynNoCPGAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]

#A #NONSYN #CPG
ZanANoSynCPGAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="a"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]

#T #NONSYN #CPG
ZanTNoSynCPGAA <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="t"&OverviewDFZanini$makesCpG==1&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]
       
###################################################
##################################################
#no big AA change

#C #NONSYN no big AA change
ZanCNoSynNOAA <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]



################################################
################################################
#G #NONSYN no big AA change
ZanGNoSynNOAA <- OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==0]



############################
############################
#C #NONSYN bigAAChange
ZanCNONSynBigAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="c"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]


###################
###################
#G #NONSYN bigAAChange
ZanGNonSynBigAA <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="nonsyn"&OverviewDFZanini$WTnt=="g"&OverviewDFZanini$makesCpG==0&OverviewDFZanini$num<=297&OverviewDFZanini$bigAAChange==1]


########################
######################
#nonsense
nonsense <-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="stop"&OverviewDFZanini$num<=297]


#####################
#####################
#resistance
resistance<-OverviewDFZanini$num[OverviewDFZanini$TypeOfSite=="res"&OverviewDFZanini$num<=297]


```




#Graphing both Zanini and Bacheler

```{r}
#Everything
# A/T/C Syn No CPG
#Plotting both Zanini and bacheler's fitness cost together.

#pdf("../Output/EstSelCoeffPROZanBach.pdf",width=12,height=8)
par(mfrow=c(1,1))

linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",ylim=c(log(0.000001),log(1)),xlim=c(log(0.000001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
     #ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.000001, 0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.000001,0.00001,0.0001, 0.0010, 0.0100, 0.1000,1.0000)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)
axis(2,labels = c(0.000001,0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.000001,0.00001,0.0001, 0.0010, 0.0100, 0.1000,1.000)),las=1)


#A #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanASynNOCPG]),log(OverviewDF$EstSelCoeff[BachASynNoCPGNEW]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#T #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTSynNoCPG]),log(OverviewDF$EstSelCoeff[BachTSynNOCPGNEW]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanCSynNoCPG]),log(OverviewDF$EstSelCoeff[ZanCSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

points(log(1*10^-6),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[11])
text(log(1*10^-6),log(3.4*10^-6),pos=4,"A/T/C, syn, no CpG")

#######
#A #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanASynCPG]),log(OverviewDF$EstSelCoeff[ZanASynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

#T #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTSynCPG]),log(OverviewDF$EstSelCoeff[ZanTSynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

points(log(1*10^-6),log(2.2*10^-6),pch=24,bg=brewer.pal(11, "Spectral")[10])
text(log(1*10^-6),log(2.2*10^-6),pos=4,"A/T, syn, CpG")
######
#G #SYN #No CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanGSynNOCPG]),log(OverviewDF$EstSelCoeff[ZanGSynNOCPG]),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(log(1*10^-6),log(1.4*10^-6),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(log(1*10^-6),log(1.4*10^-6),pos=4,"G, syn")


#####

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANonSynNOCPG]),log(OverviewDF$EstSelCoeff[ZanANonSynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

points(log(1*10^-5),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(log(1*10^-5),log(3.4*10^-6),pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNonSynNoCPG ]),log(OverviewDF$EstSelCoeff[ZanTNonSynNoCPG ]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANonSynCPG]),log(OverviewDF$EstSelCoeff[ZanANonSynCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
 
####

#With big AA change

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[ZanANoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

points(log(1*10^-5),log(2.2*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(log(1*10^-5),log(2.2*10^-6),pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[ZanTNoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANoSynCPGAA]),log(OverviewDF$EstSelCoeff[ZanANoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#T #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNoSynCPGAA]),log(OverviewDF$EstSelCoeff[ZanTNoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

########

#no big AA change

#C #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[ZanCNoSynNOAA]),log(OverviewDF$EstSelCoeff[ZanCNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)

points(log(1*10^-5),log(1.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(log(1*10^-5),log(1.4*10^-6),pos=4,"C, non-syn, no drastic AA change")

######
#G #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[ZanGNoSynNOAA]),log(OverviewDF$EstSelCoeff[ZanGNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)

points(log(1*10^-3),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(log(1*10^-3),log(3.4*10^-6),pos=4,"G, non-syn, no drastic AA change")

#######
#C #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[ZanCNONSynBigAA]),log(OverviewDF$EstSelCoeff[ZanCNONSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)

points(log(1*10^-3),log(2.2*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)
text(log(1*10^-3),log(2.2*10^-6),pos=4,"C, non-syn, drastic AA change")

#######
#G #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[ZanGNonSynBigAA]),log(OverviewDF$EstSelCoeff[ZanGNonSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)

points(log(1*10^-3),log(1.4*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
text(log(1*10^-3),log(1.4*10^-6),pos=4,"G, non-syn, drastic AA change")
#######
#nonsense
points(log(OverviewDFZanini$EstSelCoeff[nonsense]),log(OverviewDF$EstSelCoeff[nonsense]),pch=22,bg=1,col=1)

points(log(1*10^-1),log(3.4*10^-6),pch=22,bg=1,col=1)
text(log(1*10^-1),log(3.4*10^-6),pos=4,"nonsense")

#######
#resistance
points(log(OverviewDFZanini$EstSelCoeff[resistance]),log(OverviewDF$EstSelCoeff[resistance]),pch=8,bg=1,col=1)

points(log(1*10^-1),log(2.2*10^-6),pch=8,bg=1,col=1)
text(log(1*10^-1),log(2.2*10^-6),pos=4,"resistance")

#dev.off()

```
```{r}
#Everything
# A/T/C Syn No CPG
#Plotting both Zanini and bacheler's fitness cost together.

#pdf("../Output/EstSelCoeffPROZanBachNALabel.pdf",width=12,height=8)
par(mfrow=c(1,1))


linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
     #ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.001, 0.010, 0.100,1.000)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)
axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.001, 0.010, 0.100,1.000)),las=1)


#A #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanASynNOCPG]),log(OverviewDF$EstSelCoeff[BachASynNoCPGNEW]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#T #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTSynNoCPG]),log(OverviewDF$EstSelCoeff[BachTSynNOCPGNEW]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanCSynNoCPG]),log(OverviewDF$EstSelCoeff[ZanCSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

points(log(1*10^-6),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[11])
text(log(1*10^-6),log(3.4*10^-6),pos=4,"A/T/C, syn, no CpG")

#######
#A #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanASynCPG]),log(OverviewDF$EstSelCoeff[ZanASynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

#T #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTSynCPG]),log(OverviewDF$EstSelCoeff[ZanTSynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

points(log(1*10^-6),log(2.2*10^-6),pch=24,bg=brewer.pal(11, "Spectral")[10])
text(log(1*10^-6),log(2.2*10^-6),pos=4,"A/T, syn, CpG")
######
#G #SYN #No CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanGSynNOCPG]),log(OverviewDF$EstSelCoeff[ZanGSynNOCPG]),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])

points(log(1*10^-6),log(1.4*10^-6),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
text(log(1*10^-6),log(1.4*10^-6),pos=4,"G, syn")


#####

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANonSynNOCPG]),log(OverviewDF$EstSelCoeff[ZanANonSynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

points(log(1*10^-5),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
text(log(1*10^-5),log(3.4*10^-6),pos=4,"A/T, non-syn, no drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNonSynNoCPG ]),log(OverviewDF$EstSelCoeff[ZanTNonSynNoCPG ]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANonSynCPG]),log(OverviewDF$EstSelCoeff[ZanANonSynCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)
 
####

#With big AA change

#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[ZanANoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

points(log(1*10^-5),log(2.2*10^-6),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)
text(log(1*10^-5),log(2.2*10^-6),pos=4,"A/T, non-syn, drastic AA change")

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[ZanTNoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANoSynCPGAA]),log(OverviewDF$EstSelCoeff[ZanANoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#T #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNoSynCPGAA]),log(OverviewDF$EstSelCoeff[ZanTNoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

########

#no big AA change

#C #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[ZanCNoSynNOAA]),log(OverviewDF$EstSelCoeff[ZanCNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)

points(log(1*10^-5),log(1.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)
text(log(1*10^-5),log(1.4*10^-6),pos=4,"C, non-syn, no drastic AA change")

######
#G #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[ZanGNoSynNOAA]),log(OverviewDF$EstSelCoeff[ZanGNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)

points(log(1*10^-3),log(3.4*10^-6),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)
text(log(1*10^-3),log(3.4*10^-6),pos=4,"G, non-syn, no drastic AA change")

#######
#C #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[ZanCNONSynBigAA]),log(OverviewDF$EstSelCoeff[ZanCNONSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)


#######
#G #NONSYN bigAAChange
points(log(OverviewDFZanini$EstSelCoeff[ZanGNonSynBigAA]),log(OverviewDF$EstSelCoeff[ZanGNonSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)
#######
#nonsense
points(log(OverviewDFZanini$EstSelCoeff[nonsense]),log(OverviewDF$EstSelCoeff[nonsense]),pch=22,bg=1,col=1)

#######
#resistance
points(log(OverviewDFZanini$EstSelCoeff[resistance]),log(OverviewDF$EstSelCoeff[resistance]),pch=8,bg=1,col=1)

#dev.off()

```



```{r}
# A/T/C Syn No CPG
#Plotting both Zanini and bacheler's fitness cost together.
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)
axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)


#A #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanASynNOCPG]),log(OverviewDF$EstSelCoeff[BachASynNoCPGNEW]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#T #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTSynNoCPG]),log(OverviewDF$EstSelCoeff[BachTSynNOCPGNEW]),pch=21,bg=brewer.pal(11, "Spectral")[11])

#C #SYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanCSynNoCPG]),log(OverviewDF$EstSelCoeff[ZanCSynNoCPG]),pch=21,bg=brewer.pal(11, "Spectral")[11])

```


```{r}
#A/T Syn CPG
plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)
axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

#A #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanASynCPG]),log(OverviewDF$EstSelCoeff[ZanASynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

#T #SYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTSynCPG]),log(OverviewDF$EstSelCoeff[ZanTSynCPG]),pch=24,bg=brewer.pal(11, "Spectral")[10])

```

```{r}
#G #SYN #No CPG
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

points(log(OverviewDFZanini$EstSelCoeff[ZanGSynNOCPG]),log(OverviewDF$EstSelCoeff[ZanGSynNOCPG]),pch=25,bg=brewer.pal(11, "Spectral")[8],col=brewer.pal(11, "RdYlGn")[11])
```

```{r}
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)


#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANonSynNOCPG]),log(OverviewDF$EstSelCoeff[ZanANonSynNOCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNonSynNoCPG ]),log(OverviewDF$EstSelCoeff[ZanTNonSynNoCPG ]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANonSynCPG]),log(OverviewDF$EstSelCoeff[ZanANonSynCPG]),pch=21,bg=brewer.pal(11, "Spectral")[7],col=2)

```

```{r}
#With big AA change
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)


#A #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[ZanANoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#T #NONSYN #no CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNoSynNoCPGAA]),log(OverviewDF$EstSelCoeff[ZanTNoSynNoCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#A #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanANoSynCPGAA]),log(OverviewDF$EstSelCoeff[ZanANoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)


#T #NONSYN #CPG
points(log(OverviewDFZanini$EstSelCoeff[ZanTNoSynCPGAA]),log(OverviewDF$EstSelCoeff[ZanTNoSynCPGAA]),pch=22,bg=brewer.pal(11, "Spectral")[5],col=2)

```

```{r}
#no big AA change
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

#C #NONSYN no big AA change
points(log(OverviewDFZanini$EstSelCoeff[ZanCNoSynNOAA]),log(OverviewDF$EstSelCoeff[ZanCNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[3],col=2)

#num site 65, 83, 187, 212
#187

```

```{r}
#G #NONSYN no big AA change
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
points(log(OverviewDFZanini$EstSelCoeff[ZanGNoSynNOAA]),log(OverviewDF$EstSelCoeff[ZanGNoSynNOAA]),pch=21,bg=brewer.pal(11, "Spectral")[1],col=2)

```

```{r}
#C #NONSYN bigAAChange
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
points(log(OverviewDFZanini$EstSelCoeff[ZanCNONSynBigAA]),log(OverviewDF$EstSelCoeff[ZanCNONSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[3],col=2)


```

```{r}
#G #NONSYN bigAAChange
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

points(log(OverviewDFZanini$EstSelCoeff[ZanGNonSynBigAA]),log(OverviewDF$EstSelCoeff[ZanGNonSynBigAA]),pch=22,bg=brewer.pal(11, "Spectral")[1],col=2)

```

```{r}
#nonsense
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

points(log(OverviewDFZanini$EstSelCoeff[nonsense]),log(OverviewDF$EstSelCoeff[nonsense]),pch=22,bg=1,col=1)

log(OverviewDFZanini$EstSelCoeff[nonsense])
OverviewDFZanini$colMeansTsZanini[nonsense]
#Num site 52, 125, 126, 172, 181, 274
# look to site 181

```
```{r}
#resistance
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

points(log(OverviewDFZanini$EstSelCoeff[resistance]),log(OverviewDF$EstSelCoeff[resistance]),pch=8,bg=1,col=1)

```

```{r}
linex <- c(10^-5, 10^-4, 10^-3, 10^-2, 10^-1, 1)

plot(log(linex),log(linex), main = "Bacheler Protease Cost Vs Zanini Protease Cost",
     ylim=c(log(0.00001),log(1)),xlim=c(log(0.00001), log(1)), xlab = "Zanini Protease Cost", ylab = "Bacheler Protease Cost" , yaxt = "n", xaxt = "n", type= "l", lwd = 2)
axis(1,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)
#axis(2,labels = c(0.0001, 0.001, 0.01, 0.1,1.0), at = log(c(0.0001, 0.0011, 0.0101,0.1001,1.0001)),las=1)

axis(2,labels = c(0.00001, 0.0001, 0.001, 0.01, 0.1, 1.0), at = log(c(0.00001,0.0001, 0.0011, 0.0101, 0.1001,1.0001)),las=1)

points(log(OverviewDFZanini$EstSelCoeff[resistance]),log(OverviewDF$EstSelCoeff[resistance]),pch=8,bg=1,col=1)

OverviewDFZanini$num[resistance]
```

```{r}
#GT's notes 5/4/17
#180: T syn, no CpG => cost: -5.75  freq: 0.0035080095
#181: nonsense => cost:  -6.547177     freq:  0.01680428
#182:A, non???syn, drastic AA change/ CpG => cost: -3.549319 freq:  0.0003861647
```

